#!/usr/bin/env bash
set -euo pipefail

_on_error() {
  trap '' ERR
  line_path=$(caller)
  line=${line_path% *}
  path=${line_path#* }

  echo ""
  echo "ERR $path:$line $BASH_COMMAND exited with $1"
  exit
}
trap '_on_error $?' ERR

_shutdown() {
  trap '' TERM INT ERR

  kill 0
  wait
  exit 0
}

trap _shutdown TERM INT ERR

DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

if [[ -f "$HOME/.dekrypted.env" ]]; then
  eval $(cat "$HOME/.dekrypted.env")
fi

DEKRYPTED_MINER_INSTALL_PATH=${DEKRYPTED_MINER_INSTALL_PATH:-/root/dekrypted-miner}
DEKRYPTED_WALLET=${DEKRYPTED_WALLET:-003982AB483C7AB6410C4043C4990B17E213D9CD44F13E75A0}
DEKRYPTED_WORKER=${DEKRYPTED_WORKER:-$(hostname)}
DEKRYPTED_URL=${DEKRYPTED_URL:-bamboo://65.108.201.140:3000}
DEKRYPTED_BOMB=${DEKRYPTED_BOMB:-14400}

echo """
export DEKRYPTED_MINER_INSTALL_PATH="$DEKRYPTED_MINER_INSTALL_PATH"
export DEKRYPTED_WALLET="$DEKRYPTED_WALLET"
export DEKRYPTED_WORKER="$DEKRYPTED_WORKER"
export DEKRYPTED_URL="$DEKRYPTED_URL"
export DEKRYPTED_BOMB="$DEKRYPTED_BOMB"
""" > $HOME/.dekrypted.env

case "${1:-}" in
  run)
    cd "$DEKRYPTED_MINER_INSTALL_PATH"
    while true; do
      (
        sleep "$DEKRYPTED_BOMB"
        echo "BOMB ACTIVATED"
        killall -9 dcrptd-miner || true
      ) &
      bomb_pid=$!

      ./dcrptd-miner | tee /dev/null || true

      kill -9 $bomb_pid || true
      sleep 1
    done
  ;;
esac

apt-get update
apt-get install -y screen curl

if [[ ! -d "$DEKRYPTED_MINER_INSTALL_PATH" ]]; then
  mkdir -p "$DEKRYPTED_MINER_INSTALL_PATH"
  cd "$DEKRYPTED_MINER_INSTALL_PATH"
  if [[ ! -f /tmp/dekrypted-miner.tar.gz ]]; then
    curl -Lsf -o /tmp/dekrypted-miner.tar.gz https://github.com/De-Crypted/dcrptd-miner/releases/download/2.0/dcrptd-miner-linux-x64-2.0.tar.gz
  fi
  tar -xvof /tmp/dekrypted-miner.tar.gz
fi

cd "$DEKRYPTED_MINER_INSTALL_PATH"

cat <<EOF > "$DEKRYPTED_MINER_INSTALL_PATH/config.json"
{
    "_url": "Pool or node url. You can set multiple addresses, first one will be used as default and if connection fails miner will move to next one. Address prefix determines protocol used.",
    "url": [
        "$DEKRYPTED_URL"
    ],
    "_user": "Wallet address",
    "user": "$DEKRYPTED_WALLET.$DEKRYPTED_WORKER",
    "_retries": "Specifies how many times miner will try to connect to a specific url until selecting next",
    "retries": 1,
    "_action_after_retries_done": "Set action on what to do after all urls have been retried. Possible values: RETRY (= start again from first url), EXIT (= exits the miner)",
    "action_after_retries_done": "SHUTDOWN",
    "periodic_report": {
        "_initial_delay": "Delay in secodns to wait before first Periodic Report",
        "initial_delay": 10,
        "_report_interval": "Delay in seconds between Periodic Reports",
        "report_interval": 30
    },
    "api": {
        "_enabled": "Enable or disable api endpoint",
        "enabled": false,
        "_port": "Specify port to be used for api service",
        "port": 9000,
        "_localhost_only": "Bind api service only to localhost (127.0.0.1) address. [true / false]",
        "localhost_only": true,
        "_access_token": "Access token to provide as Authorization header to access api. Set to null to disable",
        "access_token": null
    },
    "Logging": {
        "Loglevel": {
            "Default": "Warning"
        }
    }
}
EOF

cat "$DEKRYPTED_MINER_INSTALL_PATH/config.json"

if crontab -l; then
  old_crontab=$(crontab -l)
else
  old_crontab=""
fi

case $old_crontab in
  *dekrypted*)
    echo "already in crontab"
  ;;
  *)
    printf "${old_crontab}\n@reboot screen -dmS dekrypted bash -l -c '$DIR/$0 run'\n" | crontab >/dev/null
  ;;
esac

screen -S dekrypted -X quit || true

screen -dmS dekrypted "$DIR/$0" run
screen -r dekrypted
